-- TO CREATE TABLES --

create table Country (
    id int generated by default as identity primary key,
    name varchar(255),
    code varchar(3)
);

create table Author (
    id int generated by default as identity primary key,
    first_name varchar(100),
    last_name varchar(100),
    country_id int,
    foreign key (country_id) references Country(id)
);

create table Book (
    id int generated by default as identity primary key,
    title varchar(255),
    isbn varchar(13),
    author_id int,
    foreign key (author_id) references Author(id)
);

create table BookDetails (
    id int generated by default as identity primary key,
    price decimal(10, 2),
    discount decimal(10, 2),
    is_hard_copy boolean,
    book_id int,
    foreign key (book_id) references Book(id)
);